[profile.default]
src = "contracts"
out = "out"
optimizer = true
optimizer_runs = 20000
libs = ["lib"]
test = 'test/foundry'
cache_path = 'forge-cache'
fs_permissions = [{ access = "read", path = "./out"}]
evm_version = "shanghai"

[fmt]
tab_width = 2

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }